import { markRaw } from "vue";
import {
  Block,
  IBlockDefinition,
  ISectionDefinition,
  SectionType,
  FormInputComponent,
} from "../../interface";
import { deviceStore } from "../../../store";

import GlobalForm from "./GlobalForm.vue";
import GlobalFirmware from "./GlobalFirmware.vue";
import GlobalIcon from "./GlobalIcon.vue";

const sections: Dictionary<ISectionDefinition> = {
  PreservePresetState: {
    block: Block.Global,
    key: "preservePresetState",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 1,
    component: FormInputComponent.Toggle,
    label: "Preserve preset setting",
    helpText: `When disabled, first preset will always be loaded on device power on.
      Otherwise, preset specified with "Active preset" option is remembered. This is not related to saving of configuration
      to specified preset - the configuration data is always retained even after power off.`,
  },
  DisableForcedValueRefreshAfterPresetChange: {
    block: Block.Global,
    key: "disableForcedValueRefreshAfterPresetChange",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 2,
    component: FormInputComponent.Toggle,
    label: "Disable forced value refresh after preset change",
    helpText: `If this option isn't enabled, all components will resend their current values once the preset changes.`,
  },
  EnablePresetChangeWithProgramChangeIn: {
    block: Block.Global,
    key: "enablePresetChangeWithProgramChangeIn",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 3,
    component: FormInputComponent.Toggle,
    label: "Enable preset change with MIDI Program Change In",
    helpText: `When enabled, upon receiving MIDI Program Change message (on any interface and any channel) the board will change the preset to cooresponding program change value.`,
  },

  // Sax fingering table (24 keys): hidden raw sections used by MIDI Saxophone page.
  // These use SectionType.Value so they can be bulk-fetched via GetSectionValues.
  SaxFingeringMaskLo14: {
    showIf: (): boolean => false,
    block: Block.Global,
    key: "saxFingeringMaskLo14",
    type: SectionType.Value,
    section: 3,
    component: FormInputComponent.Input,
    label: "Sax fingering mask lo14",
    helpText: "Internal",
    min: 0,
    max: 16383,
  },
  SaxFingeringMaskHi10Enable: {
    showIf: (): boolean => false,
    block: Block.Global,
    key: "saxFingeringMaskHi10Enable",
    type: SectionType.Value,
    section: 4,
    component: FormInputComponent.Input,
    label: "Sax fingering mask hi10+enable",
    helpText: "Internal",
    min: 0,
    max: 2047,
  },
  SaxFingeringNote: {
    showIf: (): boolean => false,
    block: Block.Global,
    key: "saxFingeringNote",
    type: SectionType.Value,
    section: 5,
    component: FormInputComponent.Input,
    label: "Sax fingering note",
    helpText: "Internal",
    min: 0,
    max: 127,
  },
  SaxRegisterChromaticEnable: {
    block: Block.Global,
    key: "saxRegisterChromaticEnable",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 4,
    component: FormInputComponent.Toggle,
    label: "색소폰 레지스터 크로매틱 모드",
    helpText: `활성화되면 디지털 버튼 입력이 단일 모노포닉 크로매틱 노트 스트림(레지스터 키)으로 결합됩니다.`,
  },
  SaxRegisterChromaticBaseNote: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxRegisterChromaticEnable,
    block: Block.Global,
    key: "saxRegisterChromaticBaseNote",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 5,
    min: 0,
    max: 127,
    component: FormInputComponent.Input,
    label: "색소폰 기본음 (0-127)",
    helpText: `레지스터 키 0에 대한 기본 MIDI 노트 번호입니다. 레지스터 키 인덱스는 이 값에 추가됩니다.`,
  },
  SaxRegisterChromaticTranspose: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxRegisterChromaticEnable,
    block: Block.Global,
    key: "saxRegisterChromaticTranspose",
    type: SectionType.Setting,
    section: 2,
    // 0..48 where 24 == 0 semitones (range -24..+24)
    settingIndex: 11,
    min: 0,
    max: 48,
    component: FormInputComponent.Input,
    label: "레지스터 트랜스포즈(반음) (-24..+24)",
    helpText: `레지스터 크로매틱 모드에서 전송되는 최종 노트에 반음 단위 트랜스포즈를 적용합니다.\n\n값 범위는 0..48이고, 24가 0반음(기본값)입니다. 예) 12= -12반음, 36= +12반음`,
  },
  SaxRegisterChromaticInputInvert: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxRegisterChromaticEnable,
    block: Block.Global,
    key: "saxRegisterChromaticInputInvert",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 9,
    component: FormInputComponent.Toggle,
    label: "키 입력 반전 (Active-Low)",
    helpText:
      "센서 출력이 0(LOW)일 때 ‘눌림/닫힘’으로 동작한다면 활성화하세요.",
  },
  SaxBreathControllerEnable: {
    block: Block.Global,
    key: "saxBreathControllerEnable",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 6,
    component: FormInputComponent.Toggle,
    label: "색소폰 브레스 컨트롤러 (MPXV7002DP)",
    helpText: `활성화되면 선택된 아날로그 입력이 MIDI CC(호흡/표현)에 매핑됩니다.`,
  },
  SaxBreathControllerAnalogIndex: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxBreathControllerEnable,
    block: Block.Global,
    key: "saxBreathControllerAnalogIndex",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 7,
    min: 0,
    max: 255,
    component: FormInputComponent.Input,
    label: "브레스 아날로그 인덱스 (0-255)",
    helpText: `MPXV7002DP에 사용할 아날로그 입력 인덱스입니다. (인덱스 매핑은 타겟 설정에 따라 달라질 수 있습니다.)

RP2040 Pico + native ADC 3채널 추천 구성:
- 0: 오프셋 트림(예약)
- 1: 브레스 센서(권장)
- 2: 피치 Amount(밴딩/비브라토 스케일, 예약)`,
  },
  SaxBreathControllerMidPercent: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxBreathControllerEnable,
    block: Block.Global,
    key: "saxBreathControllerMidPercent",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 10,
    min: 0,
    max: 100,
    component: FormInputComponent.Input,
    label: "브레스 오프셋(중앙값 %) (0-100)",
    helpText: `무호흡(0 압력)일 때의 센서 기준점을 ADC 전체 범위 대비 %로 설정합니다.\n\n대부분의 MPXV7002DP는 50% 근처(Vcc/2)입니다. 값이 낮으면 더 작은 압력에서도 CC가 빨리 올라가고, 값이 높으면 반대입니다.`,
  },
  SaxBreathControllerCC: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxBreathControllerEnable,
    block: Block.Global,
    key: "saxBreathControllerCC",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 8,
    component: FormInputComponent.Select,
    options: () => [
      { value: 2, text: "CC2 (Breath Controller)" },
      { value: 11, text: "CC11 (Expression)" },
      { value: 13, text: "CC2 + CC11" },
    ],
    label: "브레스 CC",
    helpText: `호흡 압력에 따라 전송할 MIDI CC를 선택합니다.`,
  },
  SaxPitchBendDeadzone: {
    showIf: (formState: FormState): boolean =>
      !!formState.saxBreathControllerEnable,
    block: Block.Global,
    key: "saxPitchBendDeadzone",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 12,
    min: 0,
    max: 2000,
    component: FormInputComponent.Input,
    label: "피치벤드 중앙 민감도(데드존) (0-2000)",
    helpText: `중립(중앙) 근처에서 피치벤드가 얼마나 둔해질지 설정합니다.\n\n값이 클수록 중앙에서 더 둔해지고, 값이 작을수록 중앙에서도 민감해집니다.\n단위는 14-bit 피치벤드 값 기준(센터 주변 ±N)입니다. 예) 100 = ±100.\n\n이 설정은 장치에 저장되며 전원을 껐다 켜도 유지됩니다.`,
  },
  ActivePreset: {
    block: Block.Global,
    key: "activePreset",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 0,
    component: FormInputComponent.Select,
    // Note: Read supported preset count from state
    options: (): any => {
      const count = deviceStore.state.supportedPresetsCount || 1;
      const options = [];
      for (let value = 0; value < count; value++) {
        options.push({
          value,
          text: String(value + 1),
        });
      }
      return options;
    },
    // Note: update separate state property (different UI segment than the form) when loading value
    onLoad: (value: number): void => {
      deviceStore.state.activePreset = value;
    },
    label: "Active preset",
    helpText: `Preset stores the entire configuration for device.`,
  },
  UseGlobalChannel: {
    block: Block.Global,
    key: "useGlobalChannel",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 13,
    component: FormInputComponent.Toggle,
    label: "Use global channel",
    helpText: `When enabled, specified global MIDI channel will be used for all components. Individual channels for components will be ignored.`,
  },
  GlobalChannel: {
    showIf: (formState: FormState): boolean => !!formState.useGlobalChannel,
    block: Block.Global,
    key: "globalChannel",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 14,
    min: 1,
    max: 17,
    component: FormInputComponent.Input,
    label: "Global channel",
    helpText: `Setting the channel to value 17 will cause sending of data on each MIDI channel, and incoming channel for LEDs and other components will be ignored.`,
  },
  StandardNoteOff: {
    block: Block.Global,
    key: "standardNoteOff",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 0,
    component: FormInputComponent.Toggle,
    label: "Standard note off",
    helpText: `When disabled, Note On with velocity 0 will be sent as note off. If enabled, true Note Off event will be sent instead.`,
  },
  RunningStatus: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "runningStatus",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 1,
    component: FormInputComponent.Toggle,
    label: "Running status",
    helpText: `This setting applies only to DIN MIDI out. When enabled,
    MIDI output bandwidth increases due to lower amount of bytes being sent. This setting can cause issues on older MIDI gear so it's best to leave it disabled.`,
  },
  MIDIClock: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "midiClock",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 15,
    component: FormInputComponent.Toggle,
    label: "Send MIDI clock",
    helpText: `This setting applies only to DIN MIDI out.
    When enabled, MIDI clock will be sent out at default BPM of 120. The tempo can be changed with buttons or encoders.`,
  },
  DinMidiState: {
    block: Block.Global,
    key: "dinMidiState",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 3,
    component: FormInputComponent.Toggle,
    label: "DIN MIDI",
    helpText: `Enable or disable DIN MIDI input and output.`,
  },
  BleMidiState: {
    block: Block.Global,
    key: "bleMidiState",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 9,
    component: FormInputComponent.Toggle,
    label: "BLE MIDI",
    helpText: `Enable or disable BLE (Bluetooth Low Energy) MIDI input and output.`,
  },
  UsbToDinThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "usbToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 4,
    component: FormInputComponent.Toggle,
    label: "USB to DIN Thru",
    helpText: `When enabled, all data received via USB will be forwarded to DIN out.`,
  },
  UsbToUsbThru: {
    block: Block.Global,
    key: "usbToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 5,
    component: FormInputComponent.Toggle,
    label: "USB to USB Thru",
    helpText: `When enabled, all data received via USB will be forwarded to USB out.`,
  },
  UsbToBleThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "usbToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 6,
    component: FormInputComponent.Toggle,
    label: "USB to BLE Thru",
    helpText: `When enabled, all data received via USB will be forwarded to BLE out.`,
  },
  DinToDinThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "dinToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 7,
    component: FormInputComponent.Toggle,
    label: "DIN to DIN Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to DIN out.`,
  },
  DinToUsbThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "dinToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 2,
    component: FormInputComponent.Toggle,
    label: "DIN to USB Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to USB out.`,
  },
  DinToBleThru: {
    showIf: (formState: FormState): boolean =>
      !!formState.dinMidiState && !!formState.bleMidiState,
    block: Block.Global,
    key: "dinToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 8,
    component: FormInputComponent.Toggle,
    label: "DIN to BLE Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to BLE out.`,
  },
  BleToDinThru: {
    showIf: (formState: FormState): boolean =>
      !!formState.dinMidiState && !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 10,
    component: FormInputComponent.Toggle,
    label: "BLE to DIN Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to DIN out.`,
  },
  BleToUsbThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 11,
    component: FormInputComponent.Toggle,
    label: "BLE to USB Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to USB out.`,
  },
  BleToBleThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 12,
    component: FormInputComponent.Toggle,
    label: "BLE to BLE Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to BLE out.`,
  },
};

export const GlobalBlock: IBlockDefinition = {
  block: Block.Global,
  title: "Global",
  routeName: "device-global",
  iconComponent: markRaw(GlobalIcon),
  sections,
  routes: [
    {
      path: "",
      name: "device-global",
      component: GlobalForm,
    },
    {
      path: "firmware-update",
      name: "device-firmware-update",
      component: GlobalFirmware,
    },
  ],
};
